### ISSUE TITLE
Add deprecation warning for contrib related documentation pages.

### ISSUE THREAD

**Issue by M0dM** [dry-python/dependencies#263]
Hi,

As I mentioned on dependencies's gitter, it would be nice to have a warning note at the top page of each contrib packages to warn about contrib package being deprecated.

M0dM

**Comment by proofit404** [comment]
Hi, thank you for the report.
The https://github.com/dry-python/dependencies/pull/193 has a single `docs/why.md` failure left. So hopefully it'll be merged soon.
At this point, it will be easier to finish the original PR. Instead of submitting a new PR and rebase the original PR against it.
Best regards, Artem.

**Comment by proofit404** [comment]
Fixed in #268
