### ISSUE TITLE
dependencies.value is not documented

### ISSUE THREAD

**Issue by festeh** [dry-python/dependencies#274]
Hi!

As sometimes I need to declare dependencies based on return value of some function, I looked for a way to specify it in the code. By pure chance I discovered `value` decorator and it seems to be what I needed. Is there a reason to not document it, maybe it's not still released? If this is ready to be released I can try to make a PR.

**Comment by proofit404** [comment]
Thank you for the feedback!

Indeed the `@value` decorator was released a long time ago. It works fine. It is covered with tests. It serves its purpose.

Due to the lack of time, it was not documented.

We have a task to do that https://github.com/dry-python/dependencies/issues/207

The PR to fix it is welcome.

You can take a look into the [Dangerfile](https://github.com/dry-python/dependencies/blob/master/dangerfile.ts) to have an idea of how to organize the PR properly.

Closing as it is a duplicate.

Have a good day :tada: 

Best regards,
Artem.
