### ISSUE TITLE
asyncio support

### ISSUE THREAD

**Issue by thedrow** [dry-python/dependencies#34]
How can I resolve dependencies that involve async I/O operations such as database connection pool creation?
Do we need to add support for it?

**Comment by proofit404** [comment]
As I mentioned in the #33, first of all, we should release things that already done.

After that, we can go forward to work on #26 

This will look like this:

```python
from dependencies import Injector, value

class Container(Injector):

    a = 1
    b = 2

    @value
    def foo(a, b):
        return a + b

assert Container.foo == 3
assert Container.let(a=2).foo == 4
```

This is very similar to the `@operation` decorator. `value` decorator takes a function and returns an intermediate class which `__new__` method will call an original function and return its result instead of the instance of this class. This is an implementation detail and probably will change in the future.

But it should get you an idea that `value` will take some arguments from the `Injector` scope, evaluate something from this arguments and return it back to the scope. All this happens during the injection process.

Probably we can pass a coroutine to the `value` decorator:

```python
import asincio
import aiopg

class App:
    def __init__(self, db):
        self.db = db

class Container(Injector):
    app = App

    loop = asyncio.get_event_loop()
    dsn = 'dbname=aiopg user=aiopg password=passwd host=127.0.0.1'

    @value
    async def db(dns):
        return await aiopg.create_pool(dsn)

assert isinstance(Container.app.db, <postgres db pool class>)
```

This is relatively easy, but this can be used only in synchronous code. (I'm not sure about `async def __getattr__(...`).

Probably you want to `await Container.foo.method()` where `foo` is a class with dependency set to the coroutine wrapped in `value`. In this case, your code will hold everything until `Container.foo` is returned.

Wrapping `foo` dependency with `operation` on the other hand should not have this problem. Since the dependency of `foo` will be instantiated coroutine and you are responsible to `await` it inside `foo.method`.

What do you think? Feel free to ask if you need further explanation :)

P.S. I'm still not sure about the whole `value` thing and await something inside it.

**Comment by proofit404** [comment]
The only asyncio related thing `value coroutines` was moved to the https://github.com/dry-python/dependencies/issues/26

**Comment by thedrow** [comment]
I forgot to ask. What happens if dependencies are async?

**Comment by proofit404** [comment]
First of all, I'll release the current version with synchronous `value` decorator.

Right after that, I'll be working on full `async` support in the dependencies including `value` decorator.
