### ISSUE TITLE
TypeContainer implementation

### ISSUE THREAD

**Issue by sobolevn** [dry-python/dependencies#74]
My desired use-case:

```python
class One(object):
     prop = 2


@final
@attr.s(frozen=True, slots=True, auto_attribs=True)
class HasDeps(object):
     _has_prop: One

     def __call__(self) -> int:
         return 10 * self._has_prop.prop   


# This can vary, and does not matter in this example:
container = TypeContainer()
container.register(One)
calc = container.build(HasDeps)
print(calc())
# => 20
```

How is `TypeContainer` is different from regular `Container`?
The main difference is in dependency resolution logic. Regular `Container` resolves dependencies based on its name. But, this requires us to:
1. Write types for dependencies (because we still want our code to be typed)
2. Follow name convention. This actually means that our names become a part of the public contract. And that's increase the complexity of the binding

`TypedContainer` should solve the second problem.

Here are some good examples of how other libraries handle this logic:
1. https://github.com/bobthemighty/punq It is almost perfect, but it is almost unsupported: https://github.com/bobthemighty/punq/issues/1
2. https://github.com/h2non/siringa uses very strange type annotations
3. https://github.com/alecthomas/injector uses extra decorators on `__init__` methods. And in this example we do not have `__init__` methods

**Comment by proofit404** [comment]
Hi,

Indeed it is a really common question. [We even have an answer to it in our FAQ](https://dependencies.readthedocs.io/en/latest/faq.html#why-do-not-use-type-annotations).

I'm not against the typing.  It will be implemented in a different way in the [linters project](https://github.com/dry-python/linters/issues).

These are my plans for now.

But I will consider to include `TypedInjector` in the project if

- [ ] we solve its mutable nature (something like `TypedInjector(A, B, C)` instead of `register` method)
- [ ] the same conflict resolution mechanism as we have for link loops and circle dependencies
- [ ] something similar to the `this`, `operation`, `value` and `Package` links
- [ ] reasonable support in all contribs packages.

Otherwise, I don't see how it will be different from existed projects you already mentioned.

Hope this makes sense.

Best regards,
Artem.

**Comment by proofit404** [comment]
At this moment I prefer not to spray effort on multiple API but focus on **one** preferred way to use this package.

This will reduce maintenance cost significantly.

Also, since we already decided to support type annotations in a different way I don't' see any benefit in the approach you described.

Best regards,
Artem.
